language: java

install: true

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - mvn clean verify
  - mvn clean package -Pbuild-for-docker -DskipTests
  - docker build -t mleenso/stackoverflow .
  - docker push mleenso/stackoverflow
  - mvn -Pjmh clean test

jdk:
  - oraclejdk11
