redis:
  image: redis
  expose:
    - 6379
elasticsearch:
  image: elasticsearch:6.6.2
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "cluster.name=docker-cluster"
    - "discovery.type=single-node"
