management:
  endpoints.web.exposure.include: '*'
  endpoint:
    mappings.enabled: true
    health.show-details: always

spring:
  application.name: stackoverflow
  jackson.serialization.write_dates_as_timestamps: false
  security.oauth2.client.registration.github:
    client-id: 74f1d32e8e1dac50232c
    client-secret: d9bb3d89607c6ebeb52b66fbd44d52b6a0496943
  data.elasticsearch:
    repositories.enbled: true
    cluster-nodes: localhost:9300
    cluster-name: docker-cluster
  json:
    remove.type.headers: true
    use.type.headers: false
  cloud.stream:
    function.definition: processor;consumer;concatHash;concatStar;process
    bindings:
      processor-in-0.destination: first
      processor-out-0.destination: second
      consumer-in-0.destination: second
      process-in-0.destination: words
      process-out-0.destination: counts
    kafka:
      default.consumer.trustedPackages: '*'
      streams:
        default.consumer:
          deserializationExceptionHandler: sendToDlq
        binder:
          autoCreateTopics: false
          configuration:
            commit.interval.ms: 1000
