spring.application.name: stackoverflow
spring.jackson.serialization.write_dates_as_timestamps: false

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    mappings.enabled: true
    health.show-details: always

spring.data.elasticsearch:
  repositories.enbled: true
  cluster-nodes: localhost:9300
  cluster-name: docker-cluster

spring.kafka.producer.properties.spring.json.add.type.headers: false
spring.kafka.consumer.properties.spring.json.trusted.packages: '*'
spring.json.trusted.packages: '*'

spring.cloud.stream:
  function.definition: processor;consumer;concatHash;concatStar;process
  bindings:
    processor-in-0.destination: first
    processor-out-0.destination: second
    consumer-in-0.destination: second
    process-in-0.destination: words
    process-out-0.destination: counts
  kafka.default.consumer.trustedPackages: '*'
  kafka.streams:
    default.consumer:
  #    valueSerde: org.springframework.kafka.support.serializer.JsonSerde
      trustedPackages: '*'
      deserializationExceptionHandler: sendToDlq
    binder:
      autoCreateTopics: false
      deserializationExceptionHandler: sendToDlq
      configuration:
        commit.interval.ms: 1000
