management:
  endpoints.web.exposure.include: '*'
  endpoint:
    mappings.enabled: true
    health.show-details: always

spring:
  application.name: stackoverflow
  jackson.serialization.write_dates_as_timestamps: false
  security.oauth2.client.registration.github:
    client-id: 74f1d32e8e1dac50232c
    client-secret: ${OAUTH_SECRET}
  json:
    remove.type.headers: true
    use.type.headers: false

amazon:
  s3:
    access-key: replace
    secret-key: replace